[ap-southeast-1]
noodle.critchley.biz

[us-east-1]
micro.critchley.biz

[us-west-2]
# Empty for now

[singapore:children]
ap-southeast-1

[america_east:children]
us-east-1

[america_west:children]
us-west-2

[america:children]
america_east
america_west

[ao]
noodle.critchley.biz

[europe:children]
eu-central-1

[eu-central-1]
chanterelle
bolete
amanita
hawthorn
spruce
birch
cedar
wednesday
larch
